# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: xpipe
services:
  app:
    image: xpipe
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1433;database=xpipe;encrypt=false
      - SPRING_LIQUIBASE_URL=jdbc:sqlserver://mssql:1433;database=xpipe;encrypt=false
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      mssql:
        condition: service_healthy
  mssql:
    extends:
      file: ./mssql.yml
      service: mssql
